const data = [
  {
    id: 8,
    name: 'Track 6 Utility Gum Sole - Low Top - Navy Peony/Gum',
    description:
      'Từ chất liệu da lộn (suede) quen thuộc, đặt nhẹ nhàng lên "nền tảng" cao su màu Gum nguyên khối, đem đến sự khác biệt mà vẫn hợp lý trên tổng thể. Tất cả chi tiết tạo nên một phiên bản Track 6 Utility Gum Sole cổ điển, đơn giản tiện dụng mà vẫn thu hút đối với những tín đồ thời trang khó tính nhất.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A67008_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A67008_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A67008_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A67008_4.jpg',
    ],
    gender: 'male',
    price: 1000,
    type: 'Shoe',
  },
  {
    id: 7,
    name: 'Ananas Track 6 Suede Moonphase - Low Top  - Winterize',
    description:
      'Dựa trên cảm hứng từ việc tái hiện những sắc xám (Grey) khác nhau hoà cùng những trạng thái ánh sáng trên bề mặt mặt trăng, Ananas Track 6 Suede Moonphase Pack sử dụng chất liệu da lộn (suede) đặc trưng, được phủ toàn bộ thân giày với tông màu sáng tối sắp xếp hài hoà hợp lý. Đây chắc chắn là một sản phẩm must have với những ai yêu thích chất suede và những gam màu Grey trung tính.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A6T007_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T007_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T007_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T007_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 2,
    name: 'Track 6 Triple White - Low Top - White',
    description:
      'Với cảm hứng từ Retro Sneakers và âm nhạc giai đoạn 1970s, Ananas Track 6 ra đời với danh hiệu là mẫu giày Cold Cement đầu tiên của Ananas - một thương hiệu giày Vulcanized. Chất liệu Storm Leather đáng giá "càn quét" toàn bộ bề mặt upper cùng những chi tiết thiết kế đặc trưng và mang nhiều ý nghĩa.  Chắc rằng, Track 6 sẽ đem đến cho bạn sự tự nhiên thú vị như chính thông điệp bài hát Let it be của huyền thoại The Beatles gửi gắm. Màu all white chắc nhiều bạn sẽ thích.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T002_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T002_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T002_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T002_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 1,
    name: 'Track 6 OG - Low Top - 70s White',
    description:
      'Với cảm hứng từ Retro Sneakers và âm nhạc giai đoạn 1970s, Ananas Track 6 ra đời với danh hiệu là mẫu giày Cold Cement đầu tiên của Ananas - một thương hiệu giày Vulcanized. Chất liệu Storm Leather đáng giá "càn quét" toàn bộ bề mặt upper cùng những chi tiết thiết kế đặc trưng và mang nhiều ý nghĩa.  Chắc rằng, Track 6 sẽ đem đến cho bạn sự tự nhiên thú vị như chính thông điệp bài hát Let it be của huyền thoại The Beatles gửi gắm.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T001_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T001_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T001_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T001_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 6,
    name: 'Ananas Track 6 Suede Moonphase - Low Top  - Fossil',
    description:
      'Dựa trên cảm hứng từ việc tái hiện những sắc xám (Grey) khác nhau hoà cùng những trạng thái ánh sáng trên bề mặt mặt trăng, Ananas Track 6 Suede Moonphase Pack sử dụng chất liệu da lộn (suede) đặc trưng, được phủ toàn bộ thân giày với tông màu sáng tối sắp xếp hài hoà hợp lý. Đây chắc chắn là một sản phẩm must have với những ai yêu thích chất suede và những gam màu Grey trung tính.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A6T006_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T006_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T006_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T006_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 4,
    name: 'Track 6 Suede Meadow - Low Top - Meadow',
    description:
      'Mang nét ngoài bắt mắt với gam màu lấy cảm hứng từ thiên nhiên mùa thu, Ananas Track 6 Suede Meadow lần này được sử chất liệu da lộn bền bỉ mà quen thuộc. Không đơn thuần chỉ đem nét mới mẻ đến cho những người yêu mến Track 6, phiên bản còn là yếu tố ấn định những khoảnh khắc đời thường thêm phần sắc màu thú vị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A6T004_1_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T004_1_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T004_1_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T004_1_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 5,
    name: 'Ananas Track 6 Suede Moonphase - Low Top  - Grey Pepple',
    description:
      'Dựa trên cảm hứng từ việc tái hiện những sắc xám (Grey) khác nhau hoà cùng những trạng thái ánh sáng trên bề mặt mặt trăng, Ananas Track 6 Suede Moonphase Pack sử dụng chất liệu da lộn (suede) đặc trưng, được phủ toàn bộ thân giày với tông màu sáng tối sắp xếp hài hoà hợp lý. Đây chắc chắn là một sản phẩm must have với những ai yêu thích chất suede và những gam màu Grey trung tính.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A6T005_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T005_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T005_3jpg',
      'https://ananas.vn/wp-content/uploads/pro_A6T005_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 3,
    name: 'Track 6 Triple Black - Low Top - Black',
    description:
      'Với cảm hứng từ Retro Sneakers và âm nhạc giai đoạn 1970s, Ananas Track 6 ra đời với danh hiệu là mẫu giày Cold Cement đầu tiên của Ananas - một thương hiệu giày Vulcanized. Chất liệu Storm Leather đáng giá "càn quét" toàn bộ bề mặt upper cùng những chi tiết thiết kế đặc trưng và mang nhiều ý nghĩa.  Chắc rắng, Track 6 sẽ đem đến cho bạn sự tự nhiên thú vị như chính thông điệp bài hát Let it be của huyền thoại The Beatles gửi gắm. Màu all black huyền bí luôn có mặt trong danh sách best seller. ',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T003_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T003_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T003_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_track6_A6T003_4.jpg',
    ],
    type: 'Shoe',
    gender: 'male',
    price: 990000,
  },
  {
    id: 9,
    name: 'Vintas Temperate - High Top - Dusty Olive',
    description:
      'Má ngoài Suede (da lộn), má trong phủ vải canvas kèm theo các chi tiết phối trộn chất da Nappa nâu trầm điềm đạm là ý đồ sắp xếp làm nên Vintas Temperate Pack. Với tông màu cảm hứng từ cỏ cây cùng khí hậu dịu mát rõ nét của vùng Ôn Đới. Điểm chốt hạ thuyết phục cho những con người sâu sắc, mang tâm hồn yêu thiên nhiên vô bờ bến. ',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_A61111_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A61111_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A61111_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_A61111_4.jpg',
    ],
    gender: 'male',
    type: 'Shoe',

    price: 770000,
  },
  {
    id: 17,
    name: 'Graphic Tee - Lucky Luke Graphic - Chili Pepper',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0017_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0017_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0017_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0017_4.jpg',
    ],
    gender: 'female',
    price: 365000,
    type: 'shirt',
  },
  {
    id: 12,
    name: "Hiphop Graphic Tee - Est. 17' Ananas - Ermine",
    description:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Ananas Est. 2017, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân. Est. '17 Ananas cũng là chiếc áo đơn giản nhất so với các mẫu cùng dòng Graphic Tee, do đó lại càng thêm phù hợp cho những ai tìm kiếm sự phá cách vừa đủ, không cần quá nổi bật.",
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0012_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0012_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0012_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0012_4.jpg',
    ],
    gender: 'female',
    price: 350000,
    type: 'shirt',
  },
  {
    id: 16,
    name: 'Graphic Tee - Lucky Luke Typo - Banana Crepe',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0016_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0016_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0016_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0016_4.jpg',
    ],
    gender: 'male',
    price: 350000,
    type: 'shirt',
  },
  {
    id: 14,
    name: 'Graphic Tee - Most Wanted Dalton - Caviar Black',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0014_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0014_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0014_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0014_4.jpg',
    ],
    gender: 'male',
    price: 350000,
    type: 'shirt',
  },
  {
    id: 18,
    name: 'Graphic Tee - Lucky Luke Typo - Chili Pepper',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0018_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0018_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0018_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0018_4.jpg',
    ],
    gender: 'male',
    price: 350000,
    type: 'shirt',
  },
  {
    id: 11,
    name: "Hiphop Graphic Tee - Est. '17 Ananas - Black",
    description:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Ananas Est. 2017, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân. Est. '17 Ananas cũng là chiếc áo đơn giản nhất so với các mẫu cùng dòng Graphic Tee, do đó lại càng thêm phù hợp cho những ai tìm kiếm sự phá cách vừa đủ, không cần quá nổi bật.",
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0011_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0011_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0011_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0011_4.jpg',
    ],
    gender: 'female',
    price: 350000,
    type: 'shirt',
  },
  {
    id: 19,
    name: 'Graphic Tee - The last album of The Beatles - White Yolk',
    description:
      "Chiếc áo Graphic Tee phiên bản giới hạn được lấy cảm hứng trực tiếp từ Album cuối cùng 'Let It Be' của nhóm nhạc The Beatles. Thiết kế kết hợp sự xuất hiện hình ảnh của đôi giày Ananas Track 6 OG, tuy đơn giản nhưng vẫn đảm bảo sự nổi bật qua phần in trước và sau. Cùng phom áo Basic thoải mái, đây chắc chắn là sự lựa chọn hợp lý để tạo điểm nhấn thú vị mà quen thuộc. ",
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0019_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0019_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0019_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0019_4.jpg',
    ],
    gender: 'female',
    price: 365000,
    type: 'shirt',
  },
  {
    id: 15,
    name: 'Graphic Tee - Lucky Luke Ending Scene - Banana Crepe',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0015_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0015_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0015_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0015_4.jpg',
    ],
    gender: 'female',
    price: 365000,
    type: 'shirt',
  },
  {
    id: 10,
    name: 'Hiphop Graphic Tee - Ananas Symbol - Black',
    description:
      'Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Discover Ananas ở trước và sau, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0010_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0010_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0010_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0010_4.jpg',
    ],
    gender: 'male',
    price: 365000,
    type: 'shirt',
  },
  {
    id: 13,
    name: 'Graphic Tee - Lucky Luke Comics - Caviar Black',
    description:
      'Những chiếc áo Ananas Graphic Tee có phom dáng thoải mái, rộng linh hoạt được kết hợp cùng hoạ tiết lấy cảm hứng từ bộ truyện tuổi thơ Lucky Luke. Đây sẽ là một mảnh ghép cho những outfit thú vị, dù đủ bộ hay mặc riêng lẻ vẫn khẳng định cá tính riêng biệt, ghi dấu ấn cho lần hợp tác quốc tế đầu tiên của Ananas.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/AGT0013_1.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0013_2.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0013_3.jpg',
      'https://ananas.vn/wp-content/uploads/AGT0013_4.jpg',
    ],
    gender: 'female',
    price: 365000,
    type: 'shirt',
  },

  {
    id: 32,
    name: 'Urbas Pop-up - Low Top - Ultra Violet',
    description:
      'Khoác lên mình gam màu tươi sáng và trẻ trung, nét nổi bật của Urbas "Pop-up" xuất hiện một cách tự nhiên, mới mẻ và đầy bất ngờ như chính nhịp sống hiện đại chốn thành thị - nơi tập trung những người trẻ năng động và sáng tạo không ngừng.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_4.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 33,
    name: 'Urbas Pop-up - Low Top - Ultra Violet',
    description:
      'Khoác lên mình gam màu tươi sáng và trẻ trung, nét nổi bật của Urbas "Pop-up" xuất hiện một cách tự nhiên, mới mẻ và đầy bất ngờ như chính nhịp sống hiện đại chốn thành thị - nơi tập trung những người trẻ năng động và sáng tạo không ngừng.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_4.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 34,
    name: 'Basas New Familiar - Low Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 35,
    name: 'Basas Mono-Black - High Top - All Black',
    description:
      'Chọn một màu đen cá tính làm chủ đạo, "Mono-Black" là tập hợp những sản phẩm đơn sắc cơ bản, mang đến cho bạn gợi ý vừa an toàn vừa cá tính, không quá nổi bật trong đám đông mà cũng chẳng nhạt nhòa trong đám bạn. ',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_5.jpg',
    ],
    gender: 'male',
    price: 490000,
    type: 'Shoe',
  },
  {
    id: 36,
    name: 'Basas New Familiar - Low Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 37,
    name: 'Basas New Familiar - High Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_5.jpg',
    ],
    gender: 'male',
    price: 350000,
    type: 'Shoe',
  },
  {
    id: 38,
    name: 'Basas New Simple Life - High Top - Moonstruck',
    description:
      'Thuộc dòng Basas với nét tối giản đặc trưng cùng khả năng kết hợp mọi outfit thường ngày, Basas "New Simple Life" dành cho những con người đơn giản nhưng không đơn điệu, bình thường mà chẳng tầm thường. Dáng High Top cá tính, hiện đại chính là sự lựa chọn dễ chịu cho những ngày vô lo, vô nghĩ.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_5.jpg',
    ],
    gender: 'male',
    price: 390000,
    type: 'Shoe',
  },
];
const hoodie = [
  {
    id: 20,
    name: 'Ananas Typo Logo Hoodie - Black',
    description:
      'Với chất liệu nỉ thể thao cao cấp được lựa chọn kĩ lưỡng để phù hợp với thời tiết "lạnh nhẹ" của những ngày cuối năm nhưng không tạo cảm giác bức bí, "Ananas Typo Logo Hoodie" sẽ mang đến một outfit năng động và cá tính dù không cần mix-match cầu kì. Đây là một chiếc áo không thể thiếu trong "hoodie season" năm nay.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0007_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0007_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0007_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0007_4.jpg',
    ],
    gender: 'female',
    price: 500000,
    type: 'hoodie',
  },
  {
    id: 21,
    name: 'Ananas Typo Logo Hoodie - White',
    description:
      'Với chất liệu nỉ thể thao cao cấp được lựa chọn kĩ lưỡng để phù hợp với thời tiết "lạnh nhẹ" của những ngày cuối năm nhưng không tạo cảm giác bức bí, "Ananas Typo Logo Hoodie" sẽ mang đến một outfit năng động và cá tính dù không cần mix-match cầu kì. Đây là một chiếc áo không thể thiếu trong "hoodie seasion" năm nay.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0008_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0008_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0008_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0008_4.jpg',
    ],
    gender: 'female',
    price: 500000,
    type: 'hoodie',
  },
  {
    id: 22,
    name: 'Ananas Typo Logo Hoodie - Citrus',
    description:
      'Với chất liệu nỉ thể thao cao cấp được lựa chọn kĩ lưỡng để phù hợp với thời tiết "lạnh nhẹ" của những ngày cuối năm nhưng không tạo cảm giác bức bí, "Ananas Typo Logo Hoodie" sẽ mang đến một outfit năng động và cá tính dù không cần mix-match cầu kì. Đây là một chiếc áo không thể thiếu trong "hoodie seasion" năm nay.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_4.jpg',
    ],
    gender: 'female',
    price: 500000,
    type: 'hoodie',
  },
  {
    id: 23,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 24,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 25,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 26,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 27,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 28,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 29,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 30,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
  {
    id: 31,
    name: 'Invisible Socks Pack - DiscoverYou - 3 Colors',
    description:
      'Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.',
    size: ['S', 'X', 'M', 'L'],
    status: 'New Arrival',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_ANS017_3.jpg',
    ],
    gender: 'female',
    price: 95000,
    type: 'socks',
  },
];

export default data;
