const data = [
  {
    id: 32,
    name: 'Urbas Pop-up - Low Top - Ultra Violet',
    description:
      'Khoác lên mình gam màu tươi sáng và trẻ trung, nét nổi bật của Urbas "Pop-up" xuất hiện một cách tự nhiên, mới mẻ và đầy bất ngờ như chính nhịp sống hiện đại chốn thành thị - nơi tập trung những người trẻ năng động và sáng tạo không ngừng.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_4.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 33,
    name: 'Urbas Pop-up - Low Top - Ultra Violet',
    description:
      'Khoác lên mình gam màu tươi sáng và trẻ trung, nét nổi bật của Urbas "Pop-up" xuất hiện một cách tự nhiên, mới mẻ và đầy bất ngờ như chính nhịp sống hiện đại chốn thành thị - nơi tập trung những người trẻ năng động và sáng tạo không ngừng.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_1.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_2.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_3.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_4.jpg',
      'https://ananas.vn/wp-content/uploads/pro_urbas_A21001_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 34,
    name: 'Basas New Familiar - Low Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 35,
    name: 'Basas Mono-Black - High Top - All Black',
    description:
      'Chọn một màu đen cá tính làm chủ đạo, "Mono-Black" là tập hợp những sản phẩm đơn sắc cơ bản, mang đến cho bạn gợi ý vừa an toàn vừa cá tính, không quá nổi bật trong đám đông mà cũng chẳng nhạt nhòa trong đám bạn. ',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61018_5.jpg',
    ],
    gender: 'male',
    price: 490000,
    type: 'Shoe',
  },
  {
    id: 36,
    name: 'Basas New Familiar - Low Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61016_5.jpg',
    ],
    gender: 'male',
    price: 320000,
    type: 'Shoe',
  },
  {
    id: 37,
    name: 'Basas New Familiar - High Top - Cordovan',
    description:
      'Mang ý nghĩa là một “người bạn thân” có thể đồng hành cùng bạn trên khắp các nẻo đường,“The Familiar” không mang đến những sản phẩm cầu kì phức tạp hay đủ phá cách để bạn phấn khích và mang khoe nó với nhiều người. Nó chỉ đơn giản là mang đến cho bạn một sự lựa chọn an toàn, đa-zi-năng cho một ngày học tập, làm việc, vui chơi bình dị.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61017_5.jpg',
    ],
    gender: 'male',
    price: 350000,
    type: 'Shoe',
  },
  {
    id: 38,
    name: 'Basas New Simple Life - High Top - Moonstruck',
    description:
      'Thuộc dòng Basas với nét tối giản đặc trưng cùng khả năng kết hợp mọi outfit thường ngày, Basas "New Simple Life" dành cho những con người đơn giản nhưng không đơn điệu, bình thường mà chẳng tầm thường. Dáng High Top cá tính, hiện đại chính là sự lựa chọn dễ chịu cho những ngày vô lo, vô nghĩ.',
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    status: 'Sale Off',
    image: [
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_1.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_2.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_3.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_4.jpg',
      'https://ananas.vn/wp-content/uploads/stu_basas_A61019_5.jpg',
    ],
    gender: 'male',
    price: 390000,
    type: 'Shoe',
  },
];
export default data;
